---
title: "bootstrap"
format: html
editor: visual
author: Katherine Lu
output-ext: html
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(boot)
data <- read.csv(here("original/finaldata.csv"))
data2017 <- subset(data, Year==2017)

#function to get med diff
getmeddiff <- function(data, indices, mort_stat) {
  sample_data <- data[complete.cases(data[,mort_stat]), ]
  sample_data <- sample_data[indices, ]
  group_meds <- tapply(sample_data[,mort_stat], sample_data$binaryconflict, FUN = median)
  meddiff <- group_meds[2] - group_meds[1]
  return(meddiff)
}

#MatMort
mat_boot <- boot(data=data2017, statistic = getmeddiff, strata = data2017$binaryconflict, R = 1000, mort_stat = 'MatMort')

mat_bootci <- boot.ci(boot.out = mat_boot, conf = 0.95, type = "bca")

#NeoMort
neo_boot <- boot(data=data2017, statistic = getmeddiff, strata = data2017$binaryconflict, R = 1000, mort_stat = 'NeoMort')

neo_bootci <- boot.ci(boot.out = neo_boot, conf = 0.95, type = "bca")

#InfMort
inf_boot <- boot(data=data2017, statistic = getmeddiff, strata = data2017$binaryconflict, R = 1000, mort_stat = 'InfMort')

inf_bootci <- boot.ci(boot.out = inf_boot, conf = 0.95, type = "bca")

#Under5Mort
under5_boot <- boot(data=data2017, statistic = getmeddiff, strata = data2017$binaryconflict, R = 1000, mort_stat = 'Under5Mort')

under5_bootci <- boot.ci(boot.out = under5_boot, conf = 0.95, type = "bca")

#store 95% CIs in vectors
variables <- c('Maternal Mortality', 'Neonatal Mortality', 'Infant Mortality', 'Under 5 Mortality')
lowerlims <- c(mat_bootci$bca[,4], neo_bootci$bca[,4], inf_bootci$bca[,4], under5_bootci$bca[,4])
upperlims <- c(mat_bootci$bca[,5], neo_bootci$bca[,5], inf_bootci$bca[,5], under5_bootci$bca[,5])
#store sample sizes for each variable
n <- c(
  nrow(data2017[complete.cases(data2017$MatMort),]),
  nrow(data2017[complete.cases(data2017$NeoMort),]),
  nrow(data2017[complete.cases(data2017$InfMort),]),
  nrow(data2017[complete.cases(data2017$Under5Mort),])
)

bcaCI <- data.frame(Variable=variables, LowerLim=lowerlims, UpperLim=upperlims, SampleSize=n)
```

```{r echo=FALSE, message=FALSE ,warning=FALSE}
#install.packages("DT")
library(DT)
datatable(
  bcaCI, 
  options = list(pageLength = 5, dom='t'),
  caption = htmltools::tags$caption("Difference in median mortality comparing countries exposed/unexposed to armed conflict: 95% CIs using BCa bootstrap with B=1000")
  )%>%
  formatCurrency(
    columns = c("LowerLim", "UpperLim"),
    currency = "",
    digits = 2
  )
```
